import { AccountCategory, ExpenseCategory, IncomeCategory, FinancialAccount, Transaction } from '../types';

export const ACCOUNT_CATEGORY_CONFIG: Record<
  AccountCategory,
  {
    label: string;
    description: string;
    group: 'LIQUID' | 'INVESTMENT' | 'CREDIT' | 'DEBT_RECEIVABLE';
    groupLabel: string;
    defaultColor: string;
    badgeBg: string;
    badgeText: string;
  }
> = {
  DEBIT_CARD: {
    label: '银行借记卡',
    description: '各大银行储蓄卡、活期存款',
    group: 'LIQUID',
    groupLabel: '流动资产',
    defaultColor: '#2563eb', // blue
    badgeBg: 'bg-blue-500/10',
    badgeText: 'text-blue-400 border-blue-500/20',
  },
  CREDIT_CARD: {
    label: '借贷信用卡',
    description: '银行信用卡（总额度/已用/可用）',
    group: 'CREDIT',
    groupLabel: '信用负债',
    defaultColor: '#f43f5e', // rose
    badgeBg: 'bg-rose-500/10',
    badgeText: 'text-rose-400 border-rose-500/20',
  },
  ALIPAY: {
    label: '支付宝余额',
    description: '支付宝账户可用零钱',
    group: 'LIQUID',
    groupLabel: '流动资产',
    defaultColor: '#1677ff', // official alipay blue
    badgeBg: 'bg-blue-500/10',
    badgeText: 'text-blue-500 border-blue-500/20',
  },
  YUEBAO: {
    label: '余额宝',
    description: '支付宝零钱理财/货币基金',
    group: 'INVESTMENT',
    groupLabel: '理财投资',
    defaultColor: '#f97316', // orange
    badgeBg: 'bg-orange-500/10',
    badgeText: 'text-orange-400 border-orange-500/20',
  },
  FUND: {
    label: '基金理财',
    description: '公募基金、股票ETF、理财产品',
    group: 'INVESTMENT',
    groupLabel: '理财投资',
    defaultColor: '#8b5cf6', // purple
    badgeBg: 'bg-purple-500/10',
    badgeText: 'text-purple-400 border-purple-500/20',
  },
  GOLD: {
    label: '黄金理财',
    description: '积存金、实物黄金、纸黄金',
    group: 'INVESTMENT',
    groupLabel: '理财投资',
    defaultColor: '#eab308', // gold
    badgeBg: 'bg-amber-500/10',
    badgeText: 'text-amber-400 border-amber-500/20',
  },
  JD_FINANCE: {
    label: '京东金融',
    description: '京东小金库、京东理财',
    group: 'INVESTMENT',
    groupLabel: '理财投资',
    defaultColor: '#ef4444', // red
    badgeBg: 'bg-red-500/10',
    badgeText: 'text-red-400 border-red-500/20',
  },
  JD_BAITIAO: {
    label: '京东白条',
    description: '京东先用后付信贷额度',
    group: 'CREDIT',
    groupLabel: '信用负债',
    defaultColor: '#ec4899', // pink
    badgeBg: 'bg-pink-500/10',
    badgeText: 'text-pink-400 border-pink-500/20',
  },
  HUABEI: {
    label: '蚂蚁花呗',
    description: '支付宝蚂蚁花呗消费信用额度 (先享后付)',
    group: 'CREDIT',
    groupLabel: '信用负债',
    defaultColor: '#0083ff', // huabei vibrant blue
    badgeBg: 'bg-sky-500/10',
    badgeText: 'text-sky-400 border-sky-500/20',
  },
  CASH: {
    label: '现金备用金',
    description: '纸币现金、钱包备用金',
    group: 'LIQUID',
    groupLabel: '流动资产',
    defaultColor: '#10b981', // emerald
    badgeBg: 'bg-emerald-500/10',
    badgeText: 'text-emerald-400 border-emerald-500/20',
  },
  RECEIVABLE: {
    label: '借出款项 (待收回)',
    description: '借给他人暂未收回的债权',
    group: 'DEBT_RECEIVABLE',
    groupLabel: '债权借出',
    defaultColor: '#06b6d4', // cyan
    badgeBg: 'bg-cyan-500/10',
    badgeText: 'text-cyan-400 border-cyan-500/20',
  },
  PAYABLE: {
    label: '借入款项 (待偿还)',
    description: '向他人借入暂未归还的借款',
    group: 'CREDIT',
    groupLabel: '信用负债',
    defaultColor: '#a855f7', // violet
    badgeBg: 'bg-violet-500/10',
    badgeText: 'text-violet-400 border-violet-500/20',
  },
};

export const EXPENSE_CATEGORIES: ExpenseCategory[] = [
  { id: 'food', name: '餐饮美食', icon: 'UtensilsCrossed', color: '#f97316' },
  { id: 'shopping', name: '日用百货', icon: 'ShoppingBag', color: '#ec4899' },
  { id: 'transport', name: '交通出行', icon: 'Car', color: '#3b82f6' },
  { id: 'housing', name: '房租物业', icon: 'Home', color: '#8b5cf6' },
  { id: 'digital', name: '数码数码', icon: 'Laptop', color: '#06b6d4' },
  { id: 'medical', name: '医疗健康', icon: 'HeartPulse', color: '#ef4444' },
  { id: 'entertainment', name: '休闲娱乐', icon: 'Gamepad2', color: '#10b981' },
  { id: 'social', name: '人情往来', icon: 'Gift', color: '#eab308' },
  { id: 'bills', name: '充值水电气', icon: 'Zap', color: '#6366f1' },
  { id: 'repay_fee', name: '分期与手续费', icon: 'Percent', color: '#f43f5e' },
  { id: 'other_exp', name: '其他杂项', icon: 'MoreHorizontal', color: '#64748b' },
];

export const INCOME_CATEGORIES: IncomeCategory[] = [
  { id: 'salary', name: '工资薪酬', icon: 'Briefcase', color: '#10b981' },
  { id: 'bonus', name: '年终奖金', icon: 'Award', color: '#eab308' },
  { id: 'investment_yield', name: '理财分红收益', icon: 'TrendingUp', color: '#8b5cf6' },
  { id: 'sideline', name: '副业外快', icon: 'Sparkles', color: '#06b6d4' },
  { id: 'refund', name: '退款退税', icon: 'RotateCcw', color: '#3b82f6' },
  { id: 'redpacket', name: '红包礼金', icon: 'Gift', color: '#f43f5e' },
  { id: 'other_inc', name: '其他收入', icon: 'PlusCircle', color: '#64748b' },
];

export const INITIAL_DEMO_ACCOUNTS: FinancialAccount[] = [
  {
    id: 'acc-debit-cmb',
    name: '招商银行一卡通 (借记卡)',
    category: 'DEBIT_CARD',
    bankName: '招商银行',
    cardNumberLast4: '8826',
    holderName: '张伟',
    cardTier: '金葵花卡',
    cardSkin: 'classic-cmb',
    cardNetwork: 'UNIONPAY',
    balance: 28450.00,
    color: '#e11d48',
    notes: '主发工资卡与日常支出绑定卡',
    updatedAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'acc-debit-icbc',
    name: '工商银行储蓄卡 (借记卡)',
    category: 'DEBIT_CARD',
    bankName: '中国工商银行',
    cardNumberLast4: '5190',
    holderName: '张伟',
    cardTier: '理财金账户',
    cardSkin: 'icbc-red',
    cardNetwork: 'UNIONPAY',
    balance: 15300.00,
    color: '#dc2626',
    notes: '房贷月供扣款与备用卡',
    updatedAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'acc-credit-cmb',
    name: '招商银行经典白金卡 (信用卡)',
    category: 'CREDIT_CARD',
    bankName: '招商银行',
    cardNumberLast4: '3372',
    holderName: 'ZHANG WEI',
    cardTier: '经典白金卡',
    cardSkin: 'platinum-dark',
    cardNetwork: 'UNIONPAY',
    balance: 8540.00, // 当前已欠款 (usedCredit)
    creditLimit: 60000.00, // 信用总额度
    usedCredit: 8540.00, // 已用
    billDay: 5, // 5号出账单
    dueDay: 25, // 25号还款日
    color: '#9f1239',
    notes: '日常餐饮刷卡、享积分与机场贵宾权益',
    updatedAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'acc-credit-citic',
    name: '中信银行悦卡信用卡 (信用卡)',
    category: 'CREDIT_CARD',
    bankName: '中信银行',
    cardNumberLast4: '6208',
    holderName: 'ZHANG WEI',
    cardTier: 'i白金信用卡',
    cardSkin: 'classic-cmb',
    cardNetwork: 'UNIONPAY',
    balance: 3200.00,
    creditLimit: 35000.00,
    usedCredit: 3200.00,
    billDay: 10,
    dueDay: 28,
    color: '#b91c1c',
    notes: '商旅酒店与加油优惠信用卡',
    updatedAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'acc-alipay',
    name: '支付宝余额',
    category: 'ALIPAY',
    bankName: '支付宝',
    holderName: '张伟 (已认证)',
    cardTier: '个人认证账户',
    cardSkin: 'alipay-blue',
    cardNetwork: 'NONE',
    balance: 3680.50,
    color: '#1677ff',
    notes: '线上扫码与小额快捷支付零钱',
    updatedAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'acc-yuebaobao',
    name: '余额宝 (天弘货币基金)',
    category: 'YUEBAO',
    bankName: '余额宝',
    holderName: '张伟',
    cardTier: '货币基金理财',
    cardSkin: 'gold-metallic',
    cardNetwork: 'NONE',
    balance: 35200.00,
    holdingProfit: 1420.50,
    color: '#f97316',
    notes: '活期闲钱自动生息，近七日年化约 1.88%',
    updatedAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'acc-fund-main',
    name: '公募基金理财组合 (ETF与混合)',
    category: 'FUND',
    bankName: '公募基金',
    holderName: '张伟',
    cardTier: '组合持仓',
    cardSkin: 'purple-aurora',
    cardNetwork: 'NONE',
    balance: 52600.00,
    holdingProfit: 4580.00,
    color: '#7c3aed',
    notes: '易方达沪深300ETF + 招商中证白酒 + 固收增强基金',
    updatedAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'acc-gold',
    name: '黄金理财 (工行积存金/实物金)',
    category: 'GOLD',
    bankName: '中国工商银行',
    holderName: '张伟',
    cardTier: '9999足金积存',
    cardSkin: 'gold-metallic',
    cardNetwork: 'NONE',
    balance: 31200.00, // 52g * 600元
    goldGrams: 52.0,
    goldUnitPrice: 600.0,
    holdingProfit: 3900.00,
    color: '#d97706',
    notes: '定投积存黄金 52克，对冲抗通胀配置',
    updatedAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'acc-jd-finance',
    name: '京东金融 (小金库活期理财)',
    category: 'JD_FINANCE',
    bankName: '京东金融',
    holderName: '张伟',
    cardTier: '小金库尊享',
    cardSkin: 'jd-red',
    cardNetwork: 'NONE',
    balance: 19800.00,
    holdingProfit: 620.00,
    color: '#ef4444',
    notes: '京东平台零钱理财，享京东购物优惠与收益',
    updatedAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'acc-jd-baitiao',
    name: '京东白条 (先享后付)',
    category: 'JD_BAITIAO',
    bankName: '京东白条',
    cardNumberLast4: '9901',
    holderName: 'ZHANG WEI',
    cardTier: '先享白条额度',
    cardSkin: 'baitiao-pink',
    cardNetwork: 'NONE',
    balance: 1850.00, // 当前待还账单
    creditLimit: 20000.00, // 白条总额度
    usedCredit: 1850.00,
    dueDay: 9, // 每月9日还款
    color: '#db2777',
    notes: '京东自营购物免息分期与白条额度',
    updatedAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'acc-cash',
    name: '钱包现金与备用金',
    category: 'CASH',
    bankName: '随身现金',
    holderName: '现金储蓄',
    cardTier: '应急备用金',
    cardSkin: 'emerald-cash',
    cardNetwork: 'NONE',
    balance: 1500.00,
    color: '#059669',
    notes: '家中抽屉备用现金与随身钱包硬币',
    updatedAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'acc-lend-out-1',
    name: '借出款 (同事张伟装修周转)',
    category: 'RECEIVABLE',
    balance: 10000.00,
    counterparty: '张伟',
    dueDate: '2026-10-15',
    isSettled: false,
    color: '#0891b2',
    notes: '借出装修暂借款，预计10月中旬随年终奖一次性归还',
    updatedAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'acc-borrow-in-1',
    name: '借入款 (表哥急用垫付暂存)',
    category: 'PAYABLE',
    balance: 4000.00,
    counterparty: '李表哥',
    dueDate: '2026-11-20',
    isSettled: false,
    color: '#9333ea',
    notes: '聚会垫付借入，约好11月底前微信转账结清',
    updatedAt: '2026-08-16T10:00:00Z',
  },
];

export const INITIAL_DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    type: 'INCOME',
    amount: 18500.00,
    date: '2026-08-10',
    time: '09:30',
    accountId: 'acc-debit-cmb',
    category: '工资薪酬',
    tag: '月度固定',
    description: '8月份税后工资与岗位绩效发放',
    merchant: '科技集团薪酬代发',
    createdAt: '2026-08-10T09:30:00Z',
  },
  {
    id: 'tx-2',
    type: 'EXPENSE',
    amount: 268.00,
    date: '2026-08-15',
    time: '18:45',
    accountId: 'acc-credit-cmb',
    category: '餐饮美食',
    tag: '周末聚餐',
    description: '周末家庭日式烤肉聚餐',
    merchant: '赤坂炙烤料理',
    createdAt: '2026-08-15T18:45:00Z',
  },
  {
    id: 'tx-3',
    type: 'EXPENSE',
    amount: 589.00,
    date: '2026-08-14',
    time: '20:10',
    accountId: 'acc-jd-baitiao',
    category: '日用百货',
    tag: '家居消耗',
    description: '京东自营购买空气炸锅配件与厨房耗材',
    merchant: '京东自营旗舰店',
    createdAt: '2026-08-14T20:10:00Z',
  },
  {
    id: 'tx-4',
    type: 'REPAYMENT',
    amount: 4500.00,
    date: '2026-08-12',
    time: '14:20',
    accountId: 'acc-debit-cmb',
    targetAccountId: 'acc-credit-cmb',
    category: '还信用卡',
    description: '从招行借记卡还款至招行信用卡 (恢复额度)',
    createdAt: '2026-08-12T14:20:00Z',
  },
  {
    id: 'tx-5',
    type: 'TRANSFER',
    amount: 5000.00,
    date: '2026-08-11',
    time: '11:15',
    accountId: 'acc-debit-cmb',
    targetAccountId: 'acc-yuebaobao',
    category: '零钱理财划转',
    description: '招行卡转存余额宝，赚取货币基金利息',
    createdAt: '2026-08-11T11:15:00Z',
  },
  {
    id: 'tx-6',
    type: 'EXPENSE',
    amount: 156.50,
    date: '2026-08-16',
    time: '08:20',
    accountId: 'acc-alipay',
    category: '交通出行',
    tag: '通勤',
    description: '本周滴滴快车与地铁出行汇总',
    merchant: '滴滴出行 / 地铁乘车码',
    createdAt: '2026-08-16T08:20:00Z',
  },
  {
    id: 'tx-7',
    type: 'INCOME',
    amount: 320.00,
    date: '2026-08-13',
    time: '16:00',
    accountId: 'acc-yuebaobao',
    category: '理财分红收益',
    tag: '被动收入',
    description: '余额宝与理财基金累计结息',
    merchant: '天弘基金管理有限公司',
    createdAt: '2026-08-13T16:00:00Z',
  },
  {
    id: 'tx-8',
    type: 'EXPENSE',
    amount: 3500.00,
    date: '2026-08-01',
    time: '10:00',
    accountId: 'acc-debit-icbc',
    category: '房租物业',
    tag: '固定支出',
    description: '8月份房屋租金与物业管理费',
    merchant: '房东李女士',
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'tx-9',
    type: 'LEND_OUT',
    amount: 10000.00,
    date: '2026-07-20',
    time: '15:30',
    accountId: 'acc-debit-cmb',
    targetAccountId: 'acc-lend-out-1',
    category: '人情借出款',
    counterparty: '张伟',
    description: '借给好友张伟装修临时周转金',
    createdAt: '2026-07-20T15:30:00Z',
  },
];
